### PR TITLE
[transferengine] Add MediaItem::FileDescriptor and related features. …

### PR DESCRIPTION
**Pull request by blammit**
…JB#54169 JOLLA-126

This allows resources to be added using a file descriptor.

### CODE REVIEW

**Comment by pvuorela** [comment]
Is this compatible with the transfer restart action which many transfer interface claim to support? Looks like that path fetches the transfer data from the database and you can't really store file descriptors there. If we assume that the transfer engine has access to all the transferred files, do we need much changes on this front? The most problematic case should be app getting the shared files, which skips the transfer api, right?

**Comment by blammit** [comment]
Yes I'm not sure what we want to do with the restart action. We could still support it while sailfish-share is open and the file descriptor is available, but then it's inconsistent if only supported at certain times.

Currently the file descriptor mechanism is only technically required in the app cases (email, MMS), since the transfer engine can access other files, as you mentioned, but I implemented it there as well for consistency, and because I'm not sure what we're planning for permission changes later on. If we prefer, we can restrict the file descriptor implementation to the app cases for now.

**Comment by pvuorela** [comment]
Ok, as commented elsewhere, perhaps we skip this part now.

**Comment by blammit** [comment]
No longer necessary, as discussed.

**Pull request closed without merging**
