### PR TITLE
[transfer-engine] Add links support option. JB#55268

### PR DESCRIPTION
**Pull request by mphilippov-omp**

### CODE REVIEW

**Comment by pvuorela** [comment]
There's already a mime type for links (i.e. text/x-url), don't think we add redundant api like here.

**Comment by mphilippov-omp** [comment]
> There's already a mime type for links (i.e. text/x-url), don't think we add redundant api like here.

Well, I was asked to add it (in discussion)
https://os-git.omprussia.ru/jolla/base-transferengine-plugins/-/merge_requests/5

**Comment by pvuorela** [comment]
So I'd rather go with a property for mimetypes that are not allowed, overriding any category/* wildcards.

**Comment by mphilippov-omp** [comment]
> So I'd rather go with a property for mimetypes that are not allowed, overriding any category/* wildcards.

So do you propose just text/*? Am I right?

**Comment by mphilippov-omp** [comment]
@pvuorela Please, see discussion here:
https://os-git.omprussia.ru/jolla/base-transferengine-plugins/-/merge_requests/5

**Comment by pvuorela** [comment]
Based on the discussion don't think we should be having this property

**Pull request closed without merging**
